services:
  diveteca:
    build:
      context: ..
      dockerfile: diveteca-backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:3000"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./data:/app/data
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
    restart: unless-stopped
