// Add all your exact SQL Server View names here
export const ALLOWED_VIEWS = [
    'aaron_view_AnalisisReposicionInventario',
    'aaron_view_Clientes',
    'aaron_view_CuentasPorCobrarAgrupadoClienteAnio',
    'aaron_view_CuentasPorCobrarDolarizadas',
    'aaron_view_CuentasPorCobrarDolarizadasAnio',
    'aaron_view_CuentasPorCobrarDolarizadasCliente',
    'aaron_view_DetalleComprasDolarizadas',
    'aaron_view_DetalleInventarioDolarizado',
    'aaron_view_InventarioDetalleDolarizado',
    'aaron_view_RelacionInventarioTotal',
    'aaron_view_TotalInventarioDolarizado',
    'aaron_view_ventasDolarizadasMensual',
    'aaron_view_DetalleInventarioAlmacenLoteVencimiento',
    'aaron_view_DetalleInventarioAlmacenLoteVencimientoDolarizado',
    'aaron_view_InventarioPorProducto',
    'aaron_view_InventarioPorVencimiento',
    'aaron_view_DetalleInventarioCompleto',
    'aaron_view_DetalleInventarioCompletoDolarizado',
    'aaron_view_AnalisisReposicionCritico',
    'aaron_view_AnalisisReposicionStockBajo',
    'aaron_view_AnalisisReposicionActivo',
];
