-- TODOS LOS REPORTES ESTAN HECHOS O SE PUEDEN HACER A MANO POR YEIMI

-- VENTAS MENSUALES Y ANUALES EN UNIDADES, DOLARES Y BOLIVARES (PASAR DE BOLIVARES A DOLARES CON LA TASA, AL VER POR PRODUCTO LISTAR LOS NOMBRES)
-- VENTAS VS INVENTARIO, INVENTARIOS VS FACTURAS NO ANULADAS (VENTAS POR ANHO VS INVENTARIO ACTUAL, PARA PODER VER CRECIMIENTO Y COLD STOCK)
-- FACTURAS VS FACTURAS ANULADAS (DETALLES DE LAS FACTURAS ANULADAS)
-- VENTAS POR PRODUCTO (PODER FILTRAR POR TIPO DE PRODUCTO: MEDVAL, PIZZA, OCTAPHARMA)
-- VENTAS POR CLIENTE 


-- RELACION DE VENTAS POR CLIENTE FACTURADO O POR NOTA DE ENTREGA (VER POR CLIENTE, AL VER EL DETALLE VER LOS REGLONES DE FACTURA O NOTA DE ENTREGA)

-- ALMACEN ENTECLUB (NO SE RESTA DE LAS VENTAS O DEL INVENTARIO)


-- VER LO QUE SE VA A VENCER DEL INVENTARIO POR MES (CON ALERTAS)

-- ALERTA POR DEBAJO DE INVENTARIO (SE TIENE UN MINIMO DE VENTA POR PRODUCTO SI EL INVENTARIO ESTA POR DEBAJO DE ESO NO SE PUEDE VENDER)

-- PROMEDIO DE VENTA DEL INVENTARIO (PROYECCION DE DURACION PARA LA VENTA MENSUAL, YEIMI TIENE EL CUADRO)

-- ALERTA DE CUANDO NO SE MUEVE LA MERCANCIA EN CONSIGNACION

-- DEVOLUCIONES:
-- TOTALES MENSUALES
-- POR CLIENTE (COLOCAR UNIDADES)
-- POR PRODUCTO (COLOCAR UNIDADES)
-- POR FECHA



-- THAO PREGUNTAR A YEIMI PARA VER SI HAY QUE MEZCLAR O QUE (ESPERAR A QUE YURY DECIDA QUE SE VA A HACER)